[workspace]
members = [
    "contracts/erc20",
    "contracts/caller",
]

[workspace.metadata.lints.rust.unexpected_cfgs]
level = "warn"
check-cfg = [
    'cfg(ink_abi, values("ink", "sol", "all"))'
]